### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by asood123**
This pull request adds backers and sponsors from your Open Collective https://opencollective.com/react-pwa ❤️
  
  It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
We have also added a `postinstall` script to let people know after `npm|yarn install` that you are welcoming donations (optional). [[More info](https://github.com/OpenCollective/opencollective-cli)]
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

  P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

  Thank you for your great contribution to the open source community. You are awesome! 🙌
  And welcome to the open collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

### CODE REVIEW

**Comment by jhabdas** [comment]
> This collective doesn't have a host that can receive money on their behalf

I'd like to back this project, but received the above message after pluggin in my BitPay Visa card.

**Comment by thakuryash** [comment]
Hey @jhabdas Thanks, but OpenCollective is using stripe connection and Stripe is not yet supported in India. Thus we tried but failed to add host to it. We are looking for some other alternatives.

**Comment by jhabdas** [comment]
Sounds good. Something in cryptocurrency would be my preferred donation method.

**Comment by asood123** [comment]
Since you are an open source project, we can host you in USD. That way, you don't have to worry about Stripe connection. Donations would need to come via credit or debit cards and expenses would be paid out via PayPal. Would that work?

**Comment by tirthbodawala** [comment]
@asood123 That would work just fine. How shall we proceed ?

**Comment by asood123** [comment]
I enabled your collective, you should be able to receive donations now. Welcome to Open Collective!

**Comment by jhabdas** [comment]
Went for backer and hit a GQL error upon submission, but the transaction seems to have gone through as I got an email with receipt. Thanks @asood123

**Comment by jhabdas** [comment]
@tirthbodawala I've had an open ticket with GH to add BIP0021 (Bitcoin URIs) support for README but, based on my last correspondence, they're not moving on it fast enough to I personally plan to start moving my FOSS repos to another system to gain rewards in a much more simplistic fashion using Bitcoin donations. Something to consider as time goes on.

https://github.com/gitchain/gitchain

**Comment by asood123** [comment]
Bitcoin is also on our list to support at Open Collective. Hopefully coming early next year...

**Comment by jhabdas** [comment]
@asood123 great! it'll be explosive I can guarantee!! here's a lib to get you started, enabling users to donate using pretty much any token—not just bitcoin!

https://github.com/ExodusMovement/shapeshift.io

**Pull request merged**
