### PR TITLE
#13 Add Page transition animation

### PR DESCRIPTION
**Pull request by thakuryash**
Add Page transition animation as suggested by @jhabdas.

### CODE REVIEW

**Comment by dav-is** [comment]
I don’t think this is the right approach and isn’t taking advantage of the fact that this is a SPA that controls its routing (can result in MUCH cleaner transitions).

**Comment by tirthbodawala** [comment]
@dav-is, I totally agree and am trying to implement a very clean version with css transition!

**Comment by jhabdas** [comment]
@thakuryash thanks for opening! think what we were looking for here was an observation the existing css page transition may not be occurring on first load in some browsers. hope that adds some clarity—I haven't had a chance to test personally so haven't reproduced

**Comment by jhabdas** [comment]
OOps! >< hehe

**Pull request closed without merging**
