### PR TITLE
Firebase Support (DO NOT MERGE, WIP)

### PR DESCRIPTION
**Pull request by dav-is**
WIP DO NOT MERGE
=====

This is the beginning of Google Firebase support. I can't quite get it working.

I copy `dist/server.js` to `functions/server.js` and import it into `functions/index.js`

The `functions.https.onRequest(app);` seems to expect an instance of express. I'm not quite sure how I can achieve this. I think we could add a build setting somewhere so it would output this.

### CODE REVIEW

**Comment by jhabdas** [comment]
Though it's *cough* unlikely *cough* Google will ever drop support for Firebase I remember when something called Parse existed to solve similar types of _app_ domain concerns. Nevertheless it'd be cool to see an example app created with Auth integrated using the new MongoDB stuff available in Firebase. By the way, anyone hear about the IPO? Damn I totally did know it was happening until it already happened. Missed opportunities!

**Comment by dav-is** [comment]
This PR is to support Firebase Hosting and Functions. As this is something the boilerplate can support without adding deps/increasing bundle size. I might see about adding a place to put database rules too

**Comment by dav-is** [comment]
And google really seems to be pushing Firebase full throttle. They’ve already innovated so much, it wouldn’t make sense for them to just throw away that stack. I wouldn’t be terribly surprised if they raised prices after they have a lot of people locked in. Definitely a worry of mine that you’d be using their proprietary database/Auth system so migration would likely be difficult...

**Comment by dav-is** [comment]
@tirthbodawala I can't seem to figure this out...

**Comment by bytewiz** [comment]
@dav-is did you get any further with this? 😃

**Comment by dav-is** [comment]
@bytewiz I got stuck but one of the main contributors to the package promised he’d get something going for me this weekend

**Comment by tirthbodawala** [comment]
Yes all all here now for the upgrade. @dav-is & @bytewiz This weekend is all about firebase :)

**Comment by bytewiz** [comment]
@tirthbodawala What is status on this after the weekend? let me know if I can chip in 👍

**Pull request closed without merging**
